# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G8n < Formula
  desc "Type-safe environment struct generator for Go"
  homepage "https://github.com/reglyph/g8n"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reglyph/g8n/releases/download/v0.1.0/g8n_0.1.0_darwin_amd64.tar.gz"
      sha256 "15f76e0d5b4b63d4ab7d3682fa26bc61dd08660a68798b2359fff0f3c24f9b2b"

      define_method(:install) do
        bin.install "g8n"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reglyph/g8n/releases/download/v0.1.0/g8n_0.1.0_darwin_arm64.tar.gz"
      sha256 "ab09c533ed1c2e51f04138e70d205f26519e78c6c65cd30546e3a55df0380e23"

      define_method(:install) do
        bin.install "g8n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reglyph/g8n/releases/download/v0.1.0/g8n_0.1.0_linux_amd64.tar.gz"
      sha256 "2572ae015590de8d9c0a42881331903cc60ae49f0b2a2a7162dc8ea08abe8412"
      define_method(:install) do
        bin.install "g8n"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reglyph/g8n/releases/download/v0.1.0/g8n_0.1.0_linux_arm64.tar.gz"
      sha256 "b39f3d8dd4e57b31766cce2fe34c6ea5f09fa232f3cfbff444cd36ebde248b33"
      define_method(:install) do
        bin.install "g8n"
      end
    end
  end

  test do
    system "#{bin}/g8n", "-version"
  end
end
