# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G8n < Formula
  desc "Type-safe environment struct generator for Go and TypeScript"
  homepage "https://github.com/reglyph/g8n"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reglyph/g8n/releases/download/v0.2.0/g8n_0.2.0_darwin_amd64.tar.gz"
      sha256 "a8d28e0f12e6d099ea86a10278af281b22ffb64c6cf37c878c23e0c22fc62990"

      define_method(:install) do
        bin.install "g8n"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reglyph/g8n/releases/download/v0.2.0/g8n_0.2.0_darwin_arm64.tar.gz"
      sha256 "f0a09f0cab1c2141fcbe97ca73b9e030934858bb11705350a9e3a251eb6637d4"

      define_method(:install) do
        bin.install "g8n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reglyph/g8n/releases/download/v0.2.0/g8n_0.2.0_linux_amd64.tar.gz"
      sha256 "5ac92fab0416bf7545c6f80065821d1434f4dd2d10a9634a548d933222e6b5e5"
      define_method(:install) do
        bin.install "g8n"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reglyph/g8n/releases/download/v0.2.0/g8n_0.2.0_linux_arm64.tar.gz"
      sha256 "8281f30f148fb6f06af6db27bb1fdb6beda7202233bef2b0504c2c80a27985c1"
      define_method(:install) do
        bin.install "g8n"
      end
    end
  end

  test do
    system "#{bin}/g8n", "-version"
  end
end
